import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/db/db.js"
import { Header } from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AnimeVerse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
    
      <body className={`${inter.className} xl:px-12`}>
      <Header/>
        {children}
        </body>
    </html>
  );
}
