import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/db/db.js"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <header>
        <span>Animeverse</span>
        <nav>
          <ul>
            <li></li>
            <li></li>
          </ul>
        </nav>
        </header>
        {children}
        </body>
    </html>
  );
}
